"""add_inventory_module

Revision ID: 323aa6794729
Revises: a002_onboarding
Create Date: 2026-01-09 02:12:41.334710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '323aa6794729'
down_revision: Union[str, Sequence[str], None] = 'a002_onboarding'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT 1 FROM information_schema.tables WHERE table_name = '{table_name}'
    """))
    return result.fetchone() is not None


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = '{table_name}' 
        AND column_name = '{column_name}'
    """))
    return result.fetchone() is not None


def enum_exists(enum_name: str) -> bool:
    """Check if an enum type exists"""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"""
        SELECT 1 FROM pg_type WHERE typname = '{enum_name}'
    """))
    return result.fetchone() is not None


def ensure_enum(name: str, values: list):
    """Ensure an enum exists, creating it if not"""
    if not enum_exists(name):
        enum_type = postgresql.ENUM(*values, name=name)
        enum_type.create(op.get_bind())


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure Enums
    ensure_enum('unitofmeasure', ['kg', 'g', 'lt', 'ml', 'pza', 'porcion'])
    ensure_enum('transactiontype', ['purchase', 'sale', 'adjustment', 'waste'])

    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('ingredients'):
        op.create_table('ingredients',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('tenant_id', sa.UUID(), nullable=False),
            sa.Column('name', sa.String(length=128), nullable=False),
            sa.Column('sku', sa.String(length=64), nullable=True),
            sa.Column('unit', sa.Enum('kg', 'g', 'lt', 'ml', 'pza', 'porcion', name='unitofmeasure', create_type=False), nullable=False),
            sa.Column('stock_quantity', sa.Float(), nullable=False),
            sa.Column('min_stock_alert', sa.Float(), nullable=False),
            sa.Column('cost_per_unit', sa.Float(), nullable=False),
            sa.Column('modifier_link', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_ingredient_name')
        )

    if not table_exists('inventory_transactions'):
        op.create_table('inventory_transactions',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('tenant_id', sa.UUID(), nullable=False),
            sa.Column('ingredient_id', sa.UUID(), nullable=False),
            sa.Column('transaction_type', sa.Enum('purchase', 'sale', 'adjustment', 'waste', name='transactiontype', create_type=False), nullable=False),
            sa.Column('quantity', sa.Float(), nullable=False),
            sa.Column('unit', sa.Enum('kg', 'g', 'lt', 'ml', 'pza', 'porcion', name='unitofmeasure', create_type=False), nullable=False),
            sa.Column('reference_type', sa.String(length=32), nullable=True),
            sa.Column('reference_id', sa.UUID(), nullable=True),
            sa.Column('stock_after', sa.Float(), nullable=False),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('created_by', sa.UUID(), nullable=True),
            sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('recipes'):
        op.create_table('recipes',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('menu_item_id', sa.UUID(), nullable=False),
            sa.Column('ingredient_id', sa.UUID(), nullable=False),
            sa.Column('quantity', sa.Float(), nullable=False),
            sa.Column('unit', sa.Enum('kg', 'g', 'lt', 'ml', 'pza', 'porcion', name='unitofmeasure', create_type=False), nullable=False),
            sa.Column('notes', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
            sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('menu_item_id', 'ingredient_id', name='uq_recipe_item_ingredient')
        )

    if not column_exists('menu_items', 'tax_config'):
        op.add_column('menu_items', sa.Column('tax_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('menu_items', 'tax_config'):
        op.drop_column('menu_items', 'tax_config')
    
    if table_exists('recipes'):
        op.drop_table('recipes')
    if table_exists('inventory_transactions'):
        op.drop_table('inventory_transactions')
    if table_exists('ingredients'):
        op.drop_table('ingredients')
    
    # Drop enums
    if enum_exists('transactiontype'):
        sa.Enum(name='transactiontype').drop(op.get_bind())
    if enum_exists('unitofmeasure'):
        sa.Enum(name='unitofmeasure').drop(op.get_bind())
    # ### end Alembic commands ###

