"""Add total_tips and tip_amount to cash management models

Revision ID: 6644b66d24a3
Revises: a017_fix_missing_cash_tables
Create Date: 2026-02-20 20:35:36.652271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6644b66d24a3'
down_revision: Union[str, Sequence[str], None] = 'a017_fix_missing_cash_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = :table AND column_name = :col"
    ), {"table": table_name, "col": column_name})
    return result.fetchone() is not None


def index_exists(index_name: str) -> bool:
    """Check if an index exists."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = :idx"
    ), {"idx": index_name})
    return result.fetchone() is not None


def constraint_exists(constraint_name: str) -> bool:
    """Check if a constraint exists."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = :name"
    ), {"name": constraint_name})
    return result.fetchone() is not None


def upgrade() -> None:
    """Upgrade schema."""
    # These columns may already exist from a017_fix_missing_cash_tables
    if not column_exists('cash_shifts', 'total_tips'):
        op.add_column('cash_shifts', sa.Column('total_tips', sa.Float(), nullable=False, server_default='0'))
    if not column_exists('cash_transactions', 'tip_amount'):
        op.add_column('cash_transactions', sa.Column('tip_amount', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('legal_acceptances', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'legal_acceptances', 'customers', ['customer_id'], ['id'])
    op.alter_column('legal_documents', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('legal_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('menu_items', 'prep_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('order_items', 'prep_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('15'))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    # Drop indexes/constraints only if they exist
    if index_exists('ix_purchase_order_items_order_id'):
        op.drop_index(op.f('ix_purchase_order_items_order_id'), table_name='purchase_order_items')
    if constraint_exists('fk_purchase_order_items_order'):
        op.drop_constraint(op.f('fk_purchase_order_items_order'), 'purchase_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_order_items', 'purchase_orders', ['purchase_order_id'], ['id'])
    if index_exists('ix_purchase_orders_status'):
        op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    if index_exists('ix_purchase_orders_supplier_id'):
        op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    if index_exists('ix_purchase_orders_tenant_id'):
        op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    if index_exists('ix_service_requests_table_status'):
        op.drop_index(op.f('ix_service_requests_table_status'), table_name='service_requests')
    if index_exists('ix_service_requests_tenant_created'):
        op.drop_index(op.f('ix_service_requests_tenant_created'), table_name='service_requests')
    if index_exists('ix_supplier_ingredients_ingredient_id'):
        op.drop_index(op.f('ix_supplier_ingredients_ingredient_id'), table_name='supplier_ingredients')
    if index_exists('ix_supplier_ingredients_supplier_id'):
        op.drop_index(op.f('ix_supplier_ingredients_supplier_id'), table_name='supplier_ingredients')
    if index_exists('ix_suppliers_tenant_id'):
        op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    if index_exists('ix_users_pin_hash'):
        op.drop_index(op.f('ix_users_pin_hash'), table_name='users')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_pin_hash'), 'users', ['pin_hash'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_supplier_ingredients_supplier_id'), 'supplier_ingredients', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_ingredients_ingredient_id'), 'supplier_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_service_requests_tenant_created'), 'service_requests', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_service_requests_table_status'), 'service_requests', ['table_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_purchase_order_items_order'), 'purchase_order_items', 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_purchase_order_items_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('order_items', 'prep_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('menu_items', 'prep_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('legal_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('legal_documents', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'legal_acceptances', type_='foreignkey')
    op.alter_column('legal_acceptances', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('cash_transactions', 'tip_amount')
    op.drop_column('cash_shifts', 'total_tips')
    # ### end Alembic commands ###
